Env cert
outscale/COGNAC pull request #1
Opened 2023-01-19 10:13 UTC by outscale-mgo

2023-01-20 13:07 UTC, jerome-jutteau requested changes

2023-01-23 09:09 UTC, outscale-mgo commented on lib.c
> +int osc_load_cert_from_conf(const char *profile, char **cert, char **key)
up in include

2023-01-24 10:09 UTC, jerome-jutteau requested changes
need  to fix confict and env vars

2023-01-24 12:59 UTC, outscale-mgo commented
> need to fix confict and env vars

? which one ?

2023-01-26 13:30 UTC, jerome-jutteau approved these changes

2023-01-26 14:41 UTC, merged